cua:
  base_url: https://app.cua.ai/api/v1
  api_key: "${CUA_API_KEY}"
  workspace_id: null
  persona_id: null
  poll_interval: 2.0
  timeout_seconds: 240.0

preferences:
  roles: ["nurse", "front of house"]
  industries: ["hospitality", "healthcare"]
  seniority: "mid"
  locations: ["Amsterdam", "Rotterdam"]
  remote_ok: true
  onsite_ok: true
  hybrid_ok: true
  keywords_include: ["patient care", "guest experience"]
  keywords_exclude: ["unpaid", "internship"]
  languages_required: ["English"]
  languages_forbidden: ["Dutch"]
  salary_min_eur: 32000
  employment_type: "full-time"
  schedule_prefs: ["weekend"]
  company_include: ["Radboud", "Hilton"]
  company_exclude: ["Example Corp"]

logins:
  - site_name: LinkedIn
    login_url: https://www.linkedin.com/login
    credential:
      name: linkedin-default
      username: constant@brummeronline.nl
      password: "${LINKEDIN_PASSWORD}"
      totp_secret: null
    post_login_urls:
      - https://www.linkedin.com/jobs/
